/**
 * Build-time blog source.
 *
 * Articles live in Neon, but each one still has to ship as real prerendered
 * HTML for crawlers — so the published set is pulled once per build and written
 * to src/generated/posts.js, which seo.js and BlogPages.jsx import normally.
 *
 * Without DATABASE_URL (a fresh clone, CI, an offline build) it falls back to
 * the articles in src/blogPosts.static.js, so the build never depends on the
 * database being reachable.
 *
 *   npm run posts:pull     (also runs automatically before every build)
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnv } from './load-env.mjs';
import { staticBlogPosts } from '../src/blogPosts.static.js';

loadEnv();

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const outDir = join(root, 'src', 'generated');
const outFile = join(outDir, 'posts.js');
const brandDir = join(root, 'public', 'assets', 'brand');

/** Prefer a local .webp sibling when we compressed the PNG for speed. */
function preferWebp(imagePath) {
  if (!imagePath || typeof imagePath !== 'string') return imagePath;
  if (!imagePath.endsWith('.png')) return imagePath;
  const file = basename(imagePath);
  const webpName = file.replace(/\.png$/i, '.webp');
  if (existsSync(join(brandDir, webpName))) {
    return imagePath.replace(/\.png$/i, '.webp');
  }
  return imagePath;
}

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];

function dateLabel(iso) {
  const [y, m, d] = String(iso).slice(0, 10).split('-').map(Number);
  if (!y || !m || !d) return String(iso);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

/**
 * A Postgres `date` arrives as a JS Date pinned to local midnight. Reading it
 * back with toISOString() shifts it into UTC and loses a day for anyone west of
 * Greenwich — so a build on this machine and a build on Vercel would stamp
 * different dates on the same article. Use the local calendar accessors, which
 * give the stored day in both cases.
 */
function isoDate(value) {
  if (value instanceof Date) {
    const y = value.getFullYear();
    const m = String(value.getMonth() + 1).padStart(2, '0');
    const d = String(value.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  }
  return String(value ?? '').slice(0, 10);
}

function fromRow(row) {
  const date = isoDate(row.published_on);
  return {
    slug: row.slug,
    title: row.title,
    description: row.description,
    date,
    dateLabel: dateLabel(date),
    readTime: row.read_time,
    category: row.category,
    eyebrow: row.eyebrow,
    keywords: row.keywords || [],
    lead: row.lead,
    cta: row.cta,
    image: preferWebp(row.image),
    imageAlt: row.image_alt,
    takeaways: row.takeaways || [],
    sections: row.sections || [],
  };
}

async function load() {
  if (!process.env.DATABASE_URL) {
    console.log('[posts] DATABASE_URL not set — using the static articles.');
    return { posts: staticBlogPosts, source: 'static' };
  }
  try {
    const { neon } = await import('@neondatabase/serverless');
    const sql = neon(process.env.DATABASE_URL);
    const rows = await sql`
      select * from posts where published = true
      order by published_on desc, id desc
    `;
    if (!rows.length) {
      console.log('[posts] Neon has no published articles — using the static articles.');
      return { posts: staticBlogPosts, source: 'static (db empty)' };
    }
    return { posts: rows.map(fromRow), source: 'neon' };
  } catch (error) {
    // A build must not fail because the database blinked.
    console.warn(`[posts] Neon unreachable (${error.message}) — using the static articles.`);
    return { posts: staticBlogPosts, source: 'static (db error)' };
  }
}

// The site key is baked into the bundle at build time; the secret is read at
// request time. Set the secret without the site key and the browser sends no
// token while the server demands one, so every enquiry is refused. Catch that
// here, where the build log is still being read, rather than in production.
if (process.env.RECAPTCHA_SECRET_KEY && !process.env.VITE_RECAPTCHA_SITE_KEY) {
  console.warn('');
  console.warn('[recaptcha] RECAPTCHA_SECRET_KEY is set but VITE_RECAPTCHA_SITE_KEY is not.');
  console.warn('            The contact form will reject every submission with a 403.');
  console.warn('            Add VITE_RECAPTCHA_SITE_KEY to this environment and rebuild.');
  console.warn('');
}

const { posts, source } = await load();

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `/* AUTO-GENERATED by scripts/fetch-posts.mjs — do not edit by hand.\n`
  + ` * Source: ${source} · ${posts.length} article(s) · ${new Date().toISOString()}\n */\n\n`
  + `export const posts = ${JSON.stringify(posts, null, 2)};\n`,
  'utf8',
);

console.log(`[posts] wrote ${posts.length} article(s) to src/generated/posts.js from ${source}.`);
